### ISSUE TITLE
Need warnings when less toCSS throws

### ISSUE THREAD

**Issue by matthewp** [bitovi/steal#276]
Because we don't try/catch here: https://github.com/bitovi/steal/blob/master/less.js#L30

if `root.toCSS()` throws an exception you won't know why. We should wrap this in a try/catch and reject if it throws.

**Comment by m-mujica** [comment]
I guess this won't be longer relevant when #335 gets in; `root.toCSS` is no longer there and the promise will be rejected if less throws. https://github.com/bitovi/steal/pull/335/files#diff-8ecb6318cc46da5624b1b3dcd58358caR36

**Comment by m-mujica** [comment]
@matthewp closing this one... closed by #335.
