### ISSUE TITLE
Make use of npm

### ISSUE THREAD

**Issue by matthewp** [bitovi/steal#294]
This is to discuss possible ways to integrate NPM as a package source. Unlike Bower we can't know where to find dependencies with NPM from the browser.

One idea I had was to have a command built into steal-tools that allowed you to "install" the configuration for your npm deps. Maybe something like:

```shell
steal-tools install
```

Would go through your dependencies, locate the `main` module for each and add appropriate paths to the `system` object in the package.json.

**Comment by justinbmeyer** [comment]
Closing!
