### ISSUE TITLE
stealjs.com Bitovi menu links incorrect

### ISSUE THREAD

**Issue by tomgreever** [bitovi/steal#296]
This menu is using the old Bitovi.com nav and links. Should be updated to change Consulting to Development and add Design, change People to About: 
![screen shot 2014-12-10 at 12 39 55 pm](https://cloud.githubusercontent.com/assets/326843/5381732/bac5bae0-8069-11e4-82cc-bd3285a34bab.png)

**Comment by matthewp** [comment]
This is fixed.
