### ISSUE TITLE
AMD modules can't import ES6 modules

### ISSUE THREAD

**Issue by zkat** [bitovi/steal#301]
their dependency checking gets messed up and you end up with double-loads that crash.

**Comment by justinbmeyer** [comment]
@zkat Any chance you can use latest and see if this is still happening?  Latest has an updated ES6ML.  If it is still breaking, please let me know and lets get a breaking test.  Closing for now.  I'll reopen if there's more info.

**Comment by zkat** [comment]
@justinbmeyer I just merged the latest minor into a local version of my gthrive branch and nudged things around. This is still happening on this codebase for some forsaken reason, or some problem that has very similar symptoms.
