### ISSUE TITLE
"Quick Start" Guide is missing config attribute in HTML tag

### ISSUE THREAD

**Issue by booc0mtaco** [bitovi/steal#305]
The quick start guide suggests using the following SCRIPT tag:

``` 
<script src='./bower_components/steal/steal.js'
            data-main='main'></script>
```

But this doesn't include the `config` attribute, which is needed to read the `stealconfig.js` created just after this step.  This needs to be re-worked so that:

* the `stealconfig.js` is created BEFORE the HTML in the examples
* there is some documentation describing what happens without it set up (and why)
* the script tag is modified to include the `config` attribute (e.g., `config="./stealconfig.js"`)

This is important because it would lead novices down a path without any clear explanation why things aren't working.

Other docs like <http://stealjs.com/docs/steal.html> include similar examples.

**Comment by justinbmeyer** [comment]
I think the config attribute isn't necessary to read stealconfig.js. That is the default.

**Comment by matthewp** [comment]
Yes, that is an optional attribute.
