### ISSUE TITLE
Quick Start example doesn't work in Chrome

### ISSUE THREAD

**Issue by jawshooah** [bitovi/steal#306]
I followed the Quick Start guide to the letter, but wound up getting this error in the console:
```
XMLHttpRequest cannot load file://<base_dir>/stealconfig.js.
Cross origin requests are only supported for protocol schemes: http, data, chrome-extension,
https, chrome-extension-resource.
```
Using Google Chrome Version 39.0.2171.95 (64-bit).

**Comment by justinbmeyer** [comment]
There was a recent change in systemjs. If you point to the npm brach this should be fixed. Will have a release out soon.

**Comment by jawshooah** [comment]
Still seeing this problem after running
```bash
npm install bitovi/steal-tools#npm --save-dev
bower install steal#npm --save-dev
grunt build
```

**Comment by justinbmeyer** [comment]
I didn't notice that you are seeing this in chrome, not node.  You need to be hosting a fileserver.  You can't use steal directly against the filesystem as Chrome doesn't allow AJAX requests to folders outside the one the page is running from.

I'm closing, please let me know if I'm missing something.  

If it is breaking in node, run with latest in master (or point at steal-tools@0.6.0-pre.2) and let me know.  I'll reopen.  Thannks!

**Comment by Globegitter** [comment]
@justinbmeyer just ran into the same issue and I think this should at least be mentioned in the guides. Is there any chance to get support for `file://` Systemjs itself does seem to support it.

**Comment by justinbmeyer** [comment]
@Globegitter Are you sure SystemJS works?  AFAIK, (as we are using SystemJS) it still makes ajax requests to load files.  How are you using SystemJS?  What module format?

cc @matthewp
