### ISSUE TITLE
steal.js Expected identifier error in IE8

### ISSUE THREAD

**Issue by tracer99** [bitovi/steal#309]
This is for steal 0.4
steal.js and steal.production.js will not load in IE8.
steal.js throws an "Expected Identifier" error on line 5300, col 20.

tried in our project and setup a clean project using example at steal.js

**Comment by justinbmeyer** [comment]
Does SystemJS and ES6ML work in IE8?  If not, we probably are not going to support IE8.

**Comment by justinbmeyer** [comment]
Also, can you paste that line?

**Comment by tracer99** [comment]
I thought those modules were for compile time not runtime?

    return loader.import("@config").then(function() {

**Comment by tracer99** [comment]
According to this page ES6 should work in IE8+ http://guybedford.com/practical-workflows-for-es6-modules

**Comment by justinbmeyer** [comment]
Both are used for runtime.  Traceur is not.

**Comment by justinbmeyer** [comment]
Ah, this is our problem.  Any `X.import(Y)` needs to be changed to:

```js
X["import"](Y)
```

Can you look for ".import" in https://github.com/bitovi/steal/tree/master/src and submit a pull request with them changed?

**Comment by tracer99** [comment]
Will do. Thanks.

**Comment by tracer99** [comment]
I haven't gotten to the pull request. I'm trying to implement the fix to see if it works.
Your fix works but it appears that 
     $__Object$getPrototypeOf returns null.
Fixing the return to be 
    return obj.__proto__ || obj.constructor.__proto__;
seems to work but then I get a very useless error on this line:
     $__Object$getPrototypeOf(SystemLoader.prototype).constructor.call(this, options || {});
which is "Expected ']'"

**Comment by justinbmeyer** [comment]
@tracer99 I'm not sure what you mean.  There's some code that looks like:

>  $__Object$getPrototypeOf(SystemLoader.prototype).constructor.call(this, options || {});

This is not part of StealJS.  This would be a problem with ES6ML or SystemJS.  Where is this code?

**Comment by tracer99** [comment]
Sorry. I'm hacking away at steal.js 
Didn't realise it was a combination of multiple projects.
It's under System Loader(browser-loader.js)

So the above fixes the steal part, but then system loader has issues.

**Comment by justinbmeyer** [comment]
By "System Loader" do you mean:

https://github.com/ModuleLoader/es6-module-loader

You might want to create an issue there. 

```
return obj.__proto__ || obj.constructor.__proto__;
```

Are you sure that's right?  My guess is you mean: 

```
return obj.__proto__ || obj.constructor.prototype;
```

A constructor function's proto would always point to Function.prototype.  I think you want it's prototype.

**Comment by tracer99** [comment]
https://github.com/ModuleLoader/es6-module-loader/issues/282#issuecomment-70620189

I have no idea how to proceed.

**Comment by matthewp** [comment]
This should be fixed now, I'm going to run the tests in a VM to confirm.

**Comment by matthewp** [comment]
There are still some issues, namely this: https://github.com/ModuleLoader/es6-module-loader/issues/321

Working on resolving all of these.
