### ISSUE TITLE
Consistent header navigation: "DOCS" changes to "API"

### ISSUE THREAD

**Issue by cklanac** [bitovi/steal#312]
The /docs/ section is called DOCS on the http://stealjs.com/index.html. But then is renamed to API on subsequent page.

![2015-02-03_05-12-00](https://cloud.githubusercontent.com/assets/1008777/6019184/58b79d9e-ab63-11e4-8810-35b752104d6b.png)

![2015-02-03_05-13-47](https://cloud.githubusercontent.com/assets/1008777/6019195/8024a048-ab63-11e4-9231-bec6ab08c37f.png)

**Comment by matthewp** [comment]
This must have been fixed.
