### ISSUE TITLE
System.bundle should be able to take a regex

### ISSUE THREAD

**Issue by matthewp** [bitovi/steal#316]
`System.bundle = /components\/*/`

Would create a bundle for any module named "components/*"

**Comment by justinbmeyer** [comment]
Can't put regexps in json. How would that be handled?

**Comment by matthewp** [comment]
```json
{
  "bundle": {
    "pattern": "components\/*"
  }
}
```

**Comment by justinbmeyer** [comment]
Maybe standardize on globs instead of regexps and globs?

**Comment by matthewp** [comment]
Not sure what you mean.

**Comment by matthewp** [comment]
Since paths and map supports wildcard it makes more sense to use glob: https://www.npmjs.com/package/glob

```
{Array.<moduleName>|Glob}
```
