### ISSUE TITLE
Allow use of Bower and NPM plugins at the same time

### ISSUE THREAD

**Issue by matthewp** [bitovi/steal#327]
Let's first see how much work it would entail.

**Comment by justinbmeyer** [comment]
Something like:

```
// bower.json
system: {
  configDependencies: ["package.json!npm"]
}
```

(reverse for package.json)

**Comment by matthewp** [comment]
I was thinking `preDependencies`

**Comment by justinbmeyer** [comment]
Imo, pre doesn't mean anything currently in stealjs. 

These are the deps of configMain. The transpiled source will even list them. This is why I think configDependecies makes more sense.

**Comment by matthewp** [comment]
They are deps of configMain if and only if your configMain is a package.json or bower.json. That's why I think it's the wrong word, this wouldn't work in a JavaScript config. `packageDependencies` maybe?

**Comment by justinbmeyer** [comment]
These would not work with a JavaScript config. A js config can require its own deps. 

There are special properties on system that only npm and bower will use.

**Comment by matthewp** [comment]
I'm afraid people will think they can do this in a JavaScript config.

**Comment by matthewp** [comment]
Wow, this "just works" with only a couple of lines of code change to system-npm. Going to put in some additional work to make the system-bower API match system-npm's.
