### ISSUE TITLE
steal.done returns undefined if used in succeeding script tag

### ISSUE THREAD

**Issue by matthewp** [bitovi/steal#342]
The follow will throw an exception because `steal.done()` returns undefined. The reason is steal.done returns `appDeferred` which is not defined until after startup.

```html
<script src="node_modules/steal/steal.js"></script>
<script>
  steal.done().then(function() {

  });
</script>
```

I think a probable fix is to put everything inside of makeSteal in a promise, that way steal.done can return a `startupPromise` which will exist.

**Comment by m-mujica** [comment]
@matthewp and I talked about this and it's not a valid bug, so closing it.....
