### ISSUE TITLE
Calling steal.config() with no arguments should work

### ISSUE THREAD

**Issue by dylanrtt** [bitovi/steal#348]
Using v0.7.0, we can no longer use steal.config() with no arguments to get the whole config; it now throws an error instead. This feature is used internally by canJS to support the '//' prefix for URLs with can.view so that feature no longer works.

**Comment by matthewp** [comment]
Thanks for the report. What previous version were you using where this worked?

**Comment by dylanrtt** [comment]
It seems I was using the older version of StealJS at 3.3.0pre - 2013-02-06.

**Comment by matthewp** [comment]
That makes sense, I was pretty sure the `steal.config()` form is not supported in current Steal. The reason is we no longer have an underlying config object, config is set directly on the `System` object.  I think there's an open bug in Can to make `//` work with new steal.

**Comment by dylanrtt** [comment]
Ah, that must be https://github.com/bitovi/canjs/issues/1159.

**Comment by matthewp** [comment]
Yep! I'm going to close this issue since that tracks the problem. Contribution very welcome.
