### ISSUE TITLE
Steal not loading package.json

### ISSUE THREAD

**Issue by pzuraq** [bitovi/steal#349]
The latest version of StealJS is not able to find the package.json as outlined in the guides.

Steps to reproduce:

* Clone the quick-start repo.
* Update the package.json to include the latest StealJS (`^0.7.0`).
* `npm install` and `grunt build`.

The error produced:

```
Running "steal-build:bundle" (steal-build) task
OPENING: package.json!npm
steal - error loading @config. { [Error: Error loading "package.json!npm" at file:/package.json
ENOENT, open '/package.json'] errno: -2, code: 'ENOENT', path: '/package.json' }
error { [Error: Error loading "package.json!npm" at file:/package.json
ENOENT, open '/package.json'] errno: -2, code: 'ENOENT', path: '/package.json' } Error: Error loading "package.json!npm" at file:/package.json
ENOENT, open '/package.json'
    at Error (native)
steal - error loading @config. { [Error: Error loading "package.json!npm" at file:/package.json
ENOENT, open '/package.json'] errno: -2, code: 'ENOENT', path: '/package.json' }
error { [Error: Error loading "package.json!npm" at file:/package.json
ENOENT, open '/package.json'] errno: -2, code: 'ENOENT', path: '/package.json' } Error: Error loading "package.json!npm" at file:/package.json
ENOENT, open '/package.json'
    at Error (native)
```

**Comment by matthewp** [comment]
Thanks for reporting @pzuraq, I think this is caused by some changes we made to make Steal run better on Windows. I'll look into how to fix this, but as a temporary work around I bet if you do `configMain: "package.json!npm"` it will work (notice it's `configMain`).

**Comment by pzuraq** [comment]
Yep, that works perfectly :+1: Now I'm having an issue with SystemJS I think, it's not treating imports as relative paths for some reason. I'll see if I can figure it out.

**Comment by justinbmeyer** [comment]
This might be due to some changes we made. What do your paths look like?

**Comment by pzuraq** [comment]
I'm getting the following: 

```
[Error: Error loading "zap-v3@0.0.0#router" at file:/Users/*/Code/my-app/router.js
```

My main file is located at `my-app/app/app.js` and the file it's trying to import is at `my-app/app/router.js`.

**Comment by justinbmeyer** [comment]
What do your folders/files look like?  What does your import look like?

**Comment by pzuraq** [comment]
Folders look like this:

```
my-app
├── app
|   ├── app.js
|   └── router.js
├── Gruntfile.js
└── package.json
```

package.json

```
{
    ...
    "system": {
        "root": "app",
        "main": "app" 
    }
}
```

app.js 

```
import router from './router';
...
```

**Comment by matthewp** [comment]
Get rid of root and make your main be app/app

**Comment by pzuraq** [comment]
I've tried that as well, same error.



— Chris G.

**Comment by matthewp** [comment]
@pzuraq can you push the code somewhere so we can take a look?

**Comment by matthewp** [comment]
The bug is caused [here](https://github.com/bitovi/steal/blob/master/src/config.js#L54), the baseURL gets set as `file:./`.  I'm not sure how to make a relative url with the file protocol, looking now.

**Comment by matthewp** [comment]
So the file protocol only takes absolute paths, that is our bug.  I think the fix is not to append the `file:` prefix when the path is relative. This won't work on Windows but it sounds like it can't, so we'll just have to document that on windows you need to provide a full path using __dirname or something.

**Comment by justinbmeyer** [comment]
@matthewp 

> I think the fix is not to append the file: prefix when the path is relative

Couldn't we join to process.cwd() if provided a relative baseUrl?

**Comment by matthewp** [comment]
That's true, I forget that we have Node in this scenario. I'll update my PR.
